// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sponsor.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateSponsorRequest struct {
	Sponsor              *Sponsor `protobuf:"bytes,1,opt,name=sponsor,proto3" json:"sponsor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSponsorRequest) Reset()         { *m = CreateSponsorRequest{} }
func (m *CreateSponsorRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSponsorRequest) ProtoMessage()    {}
func (*CreateSponsorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{0}
}

func (m *CreateSponsorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSponsorRequest.Unmarshal(m, b)
}
func (m *CreateSponsorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSponsorRequest.Marshal(b, m, deterministic)
}
func (m *CreateSponsorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSponsorRequest.Merge(m, src)
}
func (m *CreateSponsorRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSponsorRequest.Size(m)
}
func (m *CreateSponsorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSponsorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSponsorRequest proto.InternalMessageInfo

func (m *CreateSponsorRequest) GetSponsor() *Sponsor {
	if m != nil {
		return m.Sponsor
	}
	return nil
}

type CreateSponsorResponse struct {
	Sponsor              *Sponsor `protobuf:"bytes,1,opt,name=sponsor,proto3" json:"sponsor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSponsorResponse) Reset()         { *m = CreateSponsorResponse{} }
func (m *CreateSponsorResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSponsorResponse) ProtoMessage()    {}
func (*CreateSponsorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{1}
}

func (m *CreateSponsorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSponsorResponse.Unmarshal(m, b)
}
func (m *CreateSponsorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSponsorResponse.Marshal(b, m, deterministic)
}
func (m *CreateSponsorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSponsorResponse.Merge(m, src)
}
func (m *CreateSponsorResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSponsorResponse.Size(m)
}
func (m *CreateSponsorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSponsorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSponsorResponse proto.InternalMessageInfo

func (m *CreateSponsorResponse) GetSponsor() *Sponsor {
	if m != nil {
		return m.Sponsor
	}
	return nil
}

type CreateCompanyRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Logo                 string   `protobuf:"bytes,2,opt,name=logo,proto3" json:"logo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCompanyRequest) Reset()         { *m = CreateCompanyRequest{} }
func (m *CreateCompanyRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCompanyRequest) ProtoMessage()    {}
func (*CreateCompanyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{2}
}

func (m *CreateCompanyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCompanyRequest.Unmarshal(m, b)
}
func (m *CreateCompanyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCompanyRequest.Marshal(b, m, deterministic)
}
func (m *CreateCompanyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCompanyRequest.Merge(m, src)
}
func (m *CreateCompanyRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCompanyRequest.Size(m)
}
func (m *CreateCompanyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCompanyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCompanyRequest proto.InternalMessageInfo

func (m *CreateCompanyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCompanyRequest) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

type CreateCompanyResponse struct {
	Company              *Company `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCompanyResponse) Reset()         { *m = CreateCompanyResponse{} }
func (m *CreateCompanyResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCompanyResponse) ProtoMessage()    {}
func (*CreateCompanyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{3}
}

func (m *CreateCompanyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCompanyResponse.Unmarshal(m, b)
}
func (m *CreateCompanyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCompanyResponse.Marshal(b, m, deterministic)
}
func (m *CreateCompanyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCompanyResponse.Merge(m, src)
}
func (m *CreateCompanyResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCompanyResponse.Size(m)
}
func (m *CreateCompanyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCompanyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCompanyResponse proto.InternalMessageInfo

func (m *CreateCompanyResponse) GetCompany() *Company {
	if m != nil {
		return m.Company
	}
	return nil
}

type LoginAdminRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAdminRequest) Reset()         { *m = LoginAdminRequest{} }
func (m *LoginAdminRequest) String() string { return proto.CompactTextString(m) }
func (*LoginAdminRequest) ProtoMessage()    {}
func (*LoginAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{4}
}

func (m *LoginAdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAdminRequest.Unmarshal(m, b)
}
func (m *LoginAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAdminRequest.Marshal(b, m, deterministic)
}
func (m *LoginAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAdminRequest.Merge(m, src)
}
func (m *LoginAdminRequest) XXX_Size() int {
	return xxx_messageInfo_LoginAdminRequest.Size(m)
}
func (m *LoginAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAdminRequest proto.InternalMessageInfo

func (m *LoginAdminRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginAdminRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginAdminResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Admin                *Admin   `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAdminResponse) Reset()         { *m = LoginAdminResponse{} }
func (m *LoginAdminResponse) String() string { return proto.CompactTextString(m) }
func (*LoginAdminResponse) ProtoMessage()    {}
func (*LoginAdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{5}
}

func (m *LoginAdminResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAdminResponse.Unmarshal(m, b)
}
func (m *LoginAdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAdminResponse.Marshal(b, m, deterministic)
}
func (m *LoginAdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAdminResponse.Merge(m, src)
}
func (m *LoginAdminResponse) XXX_Size() int {
	return xxx_messageInfo_LoginAdminResponse.Size(m)
}
func (m *LoginAdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAdminResponse proto.InternalMessageInfo

func (m *LoginAdminResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginAdminResponse) GetAdmin() *Admin {
	if m != nil {
		return m.Admin
	}
	return nil
}

type DeleteAdminRequest struct {
	AdminID              string   `protobuf:"bytes,1,opt,name=adminID,proto3" json:"adminID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAdminRequest) Reset()         { *m = DeleteAdminRequest{} }
func (m *DeleteAdminRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAdminRequest) ProtoMessage()    {}
func (*DeleteAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{6}
}

func (m *DeleteAdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAdminRequest.Unmarshal(m, b)
}
func (m *DeleteAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAdminRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAdminRequest.Merge(m, src)
}
func (m *DeleteAdminRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAdminRequest.Size(m)
}
func (m *DeleteAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAdminRequest proto.InternalMessageInfo

func (m *DeleteAdminRequest) GetAdminID() string {
	if m != nil {
		return m.AdminID
	}
	return ""
}

type DeleteAdminResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAdminResponse) Reset()         { *m = DeleteAdminResponse{} }
func (m *DeleteAdminResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAdminResponse) ProtoMessage()    {}
func (*DeleteAdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{7}
}

func (m *DeleteAdminResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAdminResponse.Unmarshal(m, b)
}
func (m *DeleteAdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAdminResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAdminResponse.Merge(m, src)
}
func (m *DeleteAdminResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAdminResponse.Size(m)
}
func (m *DeleteAdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAdminResponse proto.InternalMessageInfo

func (m *DeleteAdminResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type CreateAdminRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PasswordPlainText    string   `protobuf:"bytes,3,opt,name=passwordPlainText,proto3" json:"passwordPlainText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAdminRequest) Reset()         { *m = CreateAdminRequest{} }
func (m *CreateAdminRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAdminRequest) ProtoMessage()    {}
func (*CreateAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{8}
}

func (m *CreateAdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAdminRequest.Unmarshal(m, b)
}
func (m *CreateAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAdminRequest.Marshal(b, m, deterministic)
}
func (m *CreateAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAdminRequest.Merge(m, src)
}
func (m *CreateAdminRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAdminRequest.Size(m)
}
func (m *CreateAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAdminRequest proto.InternalMessageInfo

func (m *CreateAdminRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateAdminRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateAdminRequest) GetPasswordPlainText() string {
	if m != nil {
		return m.PasswordPlainText
	}
	return ""
}

type CreateAdminResponse struct {
	Admin                *Admin   `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAdminResponse) Reset()         { *m = CreateAdminResponse{} }
func (m *CreateAdminResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAdminResponse) ProtoMessage()    {}
func (*CreateAdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{9}
}

func (m *CreateAdminResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAdminResponse.Unmarshal(m, b)
}
func (m *CreateAdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAdminResponse.Marshal(b, m, deterministic)
}
func (m *CreateAdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAdminResponse.Merge(m, src)
}
func (m *CreateAdminResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAdminResponse.Size(m)
}
func (m *CreateAdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAdminResponse proto.InternalMessageInfo

func (m *CreateAdminResponse) GetAdmin() *Admin {
	if m != nil {
		return m.Admin
	}
	return nil
}

type GetAdminRequest struct {
	AdminID              string   `protobuf:"bytes,1,opt,name=adminID,proto3" json:"adminID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAdminRequest) Reset()         { *m = GetAdminRequest{} }
func (m *GetAdminRequest) String() string { return proto.CompactTextString(m) }
func (*GetAdminRequest) ProtoMessage()    {}
func (*GetAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{10}
}

func (m *GetAdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAdminRequest.Unmarshal(m, b)
}
func (m *GetAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAdminRequest.Marshal(b, m, deterministic)
}
func (m *GetAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdminRequest.Merge(m, src)
}
func (m *GetAdminRequest) XXX_Size() int {
	return xxx_messageInfo_GetAdminRequest.Size(m)
}
func (m *GetAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdminRequest proto.InternalMessageInfo

func (m *GetAdminRequest) GetAdminID() string {
	if m != nil {
		return m.AdminID
	}
	return ""
}

type GetAdminResponse struct {
	Admin                *Admin   `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAdminResponse) Reset()         { *m = GetAdminResponse{} }
func (m *GetAdminResponse) String() string { return proto.CompactTextString(m) }
func (*GetAdminResponse) ProtoMessage()    {}
func (*GetAdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{11}
}

func (m *GetAdminResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAdminResponse.Unmarshal(m, b)
}
func (m *GetAdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAdminResponse.Marshal(b, m, deterministic)
}
func (m *GetAdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdminResponse.Merge(m, src)
}
func (m *GetAdminResponse) XXX_Size() int {
	return xxx_messageInfo_GetAdminResponse.Size(m)
}
func (m *GetAdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdminResponse proto.InternalMessageInfo

func (m *GetAdminResponse) GetAdmin() *Admin {
	if m != nil {
		return m.Admin
	}
	return nil
}

type Admin struct {
	AdminID              string   `protobuf:"bytes,1,opt,name=adminID,proto3" json:"adminID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	ACL                  []string `protobuf:"bytes,5,rep,name=ACL,proto3" json:"ACL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Admin) Reset()         { *m = Admin{} }
func (m *Admin) String() string { return proto.CompactTextString(m) }
func (*Admin) ProtoMessage()    {}
func (*Admin) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{12}
}

func (m *Admin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Admin.Unmarshal(m, b)
}
func (m *Admin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Admin.Marshal(b, m, deterministic)
}
func (m *Admin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Admin.Merge(m, src)
}
func (m *Admin) XXX_Size() int {
	return xxx_messageInfo_Admin.Size(m)
}
func (m *Admin) XXX_DiscardUnknown() {
	xxx_messageInfo_Admin.DiscardUnknown(m)
}

var xxx_messageInfo_Admin proto.InternalMessageInfo

func (m *Admin) GetAdminID() string {
	if m != nil {
		return m.AdminID
	}
	return ""
}

func (m *Admin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Admin) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Admin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Admin) GetACL() []string {
	if m != nil {
		return m.ACL
	}
	return nil
}

type Sponsor struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Company              *Company `protobuf:"bytes,5,opt,name=company,proto3" json:"company,omitempty"`
	ACL                  []string `protobuf:"bytes,6,rep,name=ACL,proto3" json:"ACL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sponsor) Reset()         { *m = Sponsor{} }
func (m *Sponsor) String() string { return proto.CompactTextString(m) }
func (*Sponsor) ProtoMessage()    {}
func (*Sponsor) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{13}
}

func (m *Sponsor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sponsor.Unmarshal(m, b)
}
func (m *Sponsor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sponsor.Marshal(b, m, deterministic)
}
func (m *Sponsor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sponsor.Merge(m, src)
}
func (m *Sponsor) XXX_Size() int {
	return xxx_messageInfo_Sponsor.Size(m)
}
func (m *Sponsor) XXX_DiscardUnknown() {
	xxx_messageInfo_Sponsor.DiscardUnknown(m)
}

var xxx_messageInfo_Sponsor proto.InternalMessageInfo

func (m *Sponsor) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Sponsor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Sponsor) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Sponsor) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Sponsor) GetCompany() *Company {
	if m != nil {
		return m.Company
	}
	return nil
}

func (m *Sponsor) GetACL() []string {
	if m != nil {
		return m.ACL
	}
	return nil
}

type Company struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Logo                 string   `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Company) Reset()         { *m = Company{} }
func (m *Company) String() string { return proto.CompactTextString(m) }
func (*Company) ProtoMessage()    {}
func (*Company) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{14}
}

func (m *Company) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Company.Unmarshal(m, b)
}
func (m *Company) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Company.Marshal(b, m, deterministic)
}
func (m *Company) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Company.Merge(m, src)
}
func (m *Company) XXX_Size() int {
	return xxx_messageInfo_Company.Size(m)
}
func (m *Company) XXX_DiscardUnknown() {
	xxx_messageInfo_Company.DiscardUnknown(m)
}

var xxx_messageInfo_Company proto.InternalMessageInfo

func (m *Company) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Company) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Company) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateSponsorRequest)(nil), "proto.CreateSponsorRequest")
	proto.RegisterType((*CreateSponsorResponse)(nil), "proto.CreateSponsorResponse")
	proto.RegisterType((*CreateCompanyRequest)(nil), "proto.CreateCompanyRequest")
	proto.RegisterType((*CreateCompanyResponse)(nil), "proto.CreateCompanyResponse")
	proto.RegisterType((*LoginAdminRequest)(nil), "proto.LoginAdminRequest")
	proto.RegisterType((*LoginAdminResponse)(nil), "proto.LoginAdminResponse")
	proto.RegisterType((*DeleteAdminRequest)(nil), "proto.DeleteAdminRequest")
	proto.RegisterType((*DeleteAdminResponse)(nil), "proto.DeleteAdminResponse")
	proto.RegisterType((*CreateAdminRequest)(nil), "proto.CreateAdminRequest")
	proto.RegisterType((*CreateAdminResponse)(nil), "proto.CreateAdminResponse")
	proto.RegisterType((*GetAdminRequest)(nil), "proto.GetAdminRequest")
	proto.RegisterType((*GetAdminResponse)(nil), "proto.GetAdminResponse")
	proto.RegisterType((*Admin)(nil), "proto.Admin")
	proto.RegisterType((*Sponsor)(nil), "proto.Sponsor")
	proto.RegisterType((*Company)(nil), "proto.Company")
}

func init() { proto.RegisterFile("sponsor.proto", fileDescriptor_b93c2e50814def43) }

var fileDescriptor_b93c2e50814def43 = []byte{
	// 622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x51, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x9d, 0xb8, 0x49, 0x27, 0x34, 0x24, 0x9b, 0x90, 0xba, 0x6e, 0x40, 0xd5, 0x22, 0xa4,
	0x28, 0xa0, 0x58, 0x04, 0x09, 0x89, 0x7e, 0x20, 0xa2, 0x14, 0x21, 0xa4, 0x0a, 0xa1, 0x94, 0x03,
	0xe0, 0x34, 0xab, 0xc8, 0xc4, 0xf1, 0x86, 0xd8, 0x14, 0x2a, 0xc4, 0x0f, 0x57, 0xe0, 0x93, 0x63,
	0x71, 0x05, 0x0e, 0xc1, 0x27, 0xf2, 0x7a, 0xd6, 0xf6, 0xc6, 0x4e, 0xd5, 0x4a, 0xfd, 0x8a, 0x77,
	0x67, 0xe6, 0xbd, 0x37, 0xb3, 0x33, 0x13, 0xd8, 0x0b, 0x56, 0xdc, 0x0f, 0xf8, 0x7a, 0xb0, 0x5a,
	0xf3, 0x90, 0x13, 0x43, 0xfc, 0x58, 0xdd, 0x39, 0xe7, 0x73, 0x8f, 0xd9, 0xce, 0xca, 0xb5, 0x1d,
	0xdf, 0xe7, 0xa1, 0x13, 0xba, 0xdc, 0x0f, 0x62, 0x27, 0xfa, 0x0a, 0xda, 0xe3, 0x35, 0x73, 0x42,
	0x76, 0x16, 0xc7, 0x4e, 0xd8, 0xe7, 0x2f, 0x2c, 0x08, 0x49, 0x0f, 0x2a, 0x88, 0x66, 0x6a, 0x47,
	0x5a, 0xaf, 0x36, 0xac, 0xc7, 0x01, 0x03, 0xe9, 0x27, 0xcd, 0x74, 0x04, 0xf7, 0x36, 0x10, 0x84,
	0x85, 0xdd, 0x00, 0xe2, 0xa5, 0x14, 0x31, 0xe6, 0xcb, 0x95, 0xe3, 0x5f, 0x4a, 0x11, 0x04, 0xca,
	0xbe, 0xb3, 0x64, 0x22, 0x7c, 0x77, 0x22, 0xbe, 0xa3, 0x3b, 0x8f, 0xcf, 0xb9, 0xa9, 0xc7, 0x77,
	0xd1, 0x77, 0x2a, 0x21, 0x89, 0x4f, 0x25, 0x9c, 0xc7, 0x57, 0x1b, 0x12, 0xa4, 0xa3, 0x34, 0xd3,
	0xd7, 0xd0, 0x3c, 0xe5, 0x73, 0xd7, 0x1f, 0xcd, 0x96, 0xae, 0x2f, 0xf9, 0xdb, 0x60, 0xb0, 0xa5,
	0xe3, 0x7a, 0x28, 0x20, 0x3e, 0x10, 0x0b, 0xaa, 0x2b, 0x27, 0x08, 0xbe, 0xf2, 0xf5, 0x0c, 0x55,
	0x24, 0x67, 0xfa, 0x0e, 0x48, 0x16, 0x06, 0x65, 0xb4, 0xc1, 0x08, 0xf9, 0x82, 0xf9, 0x12, 0x47,
	0x1c, 0x08, 0x05, 0xc3, 0x89, 0xdc, 0x04, 0x48, 0x6d, 0x78, 0x07, 0xa5, 0xc5, 0xa1, 0xb1, 0x89,
	0x0e, 0x80, 0x9c, 0x30, 0x8f, 0x85, 0x4c, 0xd1, 0x65, 0x42, 0x45, 0x98, 0xdf, 0x9e, 0x20, 0xa2,
	0x3c, 0xd2, 0x47, 0xd0, 0x52, 0xfc, 0x51, 0x40, 0x1d, 0x74, 0xbe, 0x10, 0xbe, 0xd5, 0x89, 0xce,
	0x17, 0xd4, 0x03, 0x12, 0x17, 0x4c, 0x81, 0x2d, 0x2a, 0x77, 0x52, 0x02, 0x3d, 0x5b, 0x82, 0x27,
	0xd0, 0x94, 0x29, 0xbf, 0xf7, 0x1c, 0xd7, 0xff, 0xc0, 0xbe, 0x85, 0x66, 0x49, 0x78, 0xe4, 0x0d,
	0xf4, 0x05, 0xb4, 0x14, 0x36, 0x14, 0x95, 0xe4, 0xaf, 0x6d, 0xcf, 0xff, 0x31, 0xdc, 0x7d, 0xc3,
	0xc2, 0x6b, 0x26, 0xff, 0x1c, 0x1a, 0xa9, 0xf3, 0x0d, 0x48, 0x2e, 0xc1, 0x10, 0xe7, 0xed, 0xd0,
	0x49, 0x69, 0xf4, 0xa2, 0xd2, 0x94, 0xb6, 0x75, 0x47, 0x59, 0xed, 0x0e, 0xd2, 0x80, 0xd2, 0x68,
	0x7c, 0x6a, 0x1a, 0x47, 0xa5, 0xde, 0xee, 0x24, 0xfa, 0xa4, 0xbf, 0x35, 0xa8, 0xe0, 0x38, 0x44,
	0x8f, 0xe4, 0xce, 0x90, 0x58, 0x77, 0x67, 0xb7, 0xc4, 0x99, 0x19, 0x01, 0xe3, 0xca, 0x11, 0x90,
	0xea, 0x76, 0x52, 0x75, 0x23, 0xa8, 0xa0, 0xd7, 0xb5, 0xc4, 0xc9, 0xd1, 0x2c, 0xa5, 0xa3, 0x39,
	0xfc, 0x57, 0x86, 0x3a, 0x26, 0x78, 0xc6, 0xd6, 0x17, 0xee, 0x39, 0x23, 0x53, 0xa8, 0x65, 0xda,
	0x81, 0x1c, 0x48, 0x3d, 0xb9, 0x86, 0xb4, 0xac, 0x22, 0x53, 0xfc, 0xb0, 0xb4, 0xfb, 0xf3, 0xcf,
	0xdf, 0x5f, 0x7a, 0x87, 0x36, 0xed, 0x8b, 0xa7, 0x36, 0x2e, 0x12, 0x5b, 0x3c, 0xd7, 0xb1, 0xd6,
	0x27, 0x1f, 0xa1, 0x2a, 0x5b, 0x81, 0x74, 0x10, 0x65, 0xa3, 0x91, 0xac, 0xfd, 0xdc, 0x3d, 0x42,
	0x3f, 0x14, 0xd0, 0xf7, 0xc9, 0x61, 0x0e, 0xda, 0xfe, 0x8e, 0x0d, 0xf1, 0x83, 0xb8, 0x50, 0xcb,
	0x4c, 0x5a, 0x92, 0x45, 0x7e, 0x5a, 0x93, 0x2c, 0x0a, 0x06, 0x53, 0x52, 0xf5, 0xaf, 0xa4, 0x62,
	0x00, 0xe9, 0x52, 0x21, 0x26, 0xc2, 0xe5, 0xd6, 0x95, 0x75, 0x50, 0x60, 0x41, 0x1e, 0x2a, 0x78,
	0xba, 0x74, 0x3f, 0xcf, 0xe3, 0x45, 0xde, 0x51, 0xcd, 0xa6, 0xb0, 0xa7, 0x2c, 0x72, 0x72, 0xa8,
	0x94, 0x5f, 0xfd, 0x83, 0xb0, 0xba, 0xc5, 0x46, 0xe4, 0xeb, 0x08, 0xbe, 0x06, 0xad, 0x65, 0xf8,
	0x22, 0x8e, 0x4f, 0x92, 0x43, 0xf6, 0x95, 0xca, 0xa1, 0xee, 0xff, 0x0d, 0x8e, 0x8d, 0xe5, 0x4e,
	0x1f, 0x08, 0x0e, 0x93, 0xb6, 0xb2, 0x39, 0x61, 0x33, 0x1f, 0x6b, 0xfd, 0xe9, 0x8e, 0x08, 0x7e,
	0xf6, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x27, 0xee, 0x17, 0x17, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SponsorServiceClient is the client API for SponsorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SponsorServiceClient interface {
	//
	//================================================================
	//ADMIN RPC CALLS
	//================================================================
	CreateAdmin(ctx context.Context, in *CreateAdminRequest, opts ...grpc.CallOption) (*CreateAdminResponse, error)
	GetAdmin(ctx context.Context, in *GetAdminRequest, opts ...grpc.CallOption) (*GetAdminResponse, error)
	DeleteAdmin(ctx context.Context, in *DeleteAdminRequest, opts ...grpc.CallOption) (*DeleteAdminResponse, error)
	LoginAdmin(ctx context.Context, in *LoginAdminRequest, opts ...grpc.CallOption) (*LoginAdminResponse, error)
	//
	//================================================================
	//SPONSOR RPC CALLS
	//================================================================
	CreateSponsor(ctx context.Context, in *CreateSponsorRequest, opts ...grpc.CallOption) (*CreateSponsorResponse, error)
	CreateCompany(ctx context.Context, in *CreateCompanyRequest, opts ...grpc.CallOption) (*CreateCompanyResponse, error)
}

type sponsorServiceClient struct {
	cc *grpc.ClientConn
}

func NewSponsorServiceClient(cc *grpc.ClientConn) SponsorServiceClient {
	return &sponsorServiceClient{cc}
}

func (c *sponsorServiceClient) CreateAdmin(ctx context.Context, in *CreateAdminRequest, opts ...grpc.CallOption) (*CreateAdminResponse, error) {
	out := new(CreateAdminResponse)
	err := c.cc.Invoke(ctx, "/proto.SponsorService/CreateAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sponsorServiceClient) GetAdmin(ctx context.Context, in *GetAdminRequest, opts ...grpc.CallOption) (*GetAdminResponse, error) {
	out := new(GetAdminResponse)
	err := c.cc.Invoke(ctx, "/proto.SponsorService/GetAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sponsorServiceClient) DeleteAdmin(ctx context.Context, in *DeleteAdminRequest, opts ...grpc.CallOption) (*DeleteAdminResponse, error) {
	out := new(DeleteAdminResponse)
	err := c.cc.Invoke(ctx, "/proto.SponsorService/DeleteAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sponsorServiceClient) LoginAdmin(ctx context.Context, in *LoginAdminRequest, opts ...grpc.CallOption) (*LoginAdminResponse, error) {
	out := new(LoginAdminResponse)
	err := c.cc.Invoke(ctx, "/proto.SponsorService/LoginAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sponsorServiceClient) CreateSponsor(ctx context.Context, in *CreateSponsorRequest, opts ...grpc.CallOption) (*CreateSponsorResponse, error) {
	out := new(CreateSponsorResponse)
	err := c.cc.Invoke(ctx, "/proto.SponsorService/CreateSponsor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sponsorServiceClient) CreateCompany(ctx context.Context, in *CreateCompanyRequest, opts ...grpc.CallOption) (*CreateCompanyResponse, error) {
	out := new(CreateCompanyResponse)
	err := c.cc.Invoke(ctx, "/proto.SponsorService/CreateCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SponsorServiceServer is the server API for SponsorService service.
type SponsorServiceServer interface {
	//
	//================================================================
	//ADMIN RPC CALLS
	//================================================================
	CreateAdmin(context.Context, *CreateAdminRequest) (*CreateAdminResponse, error)
	GetAdmin(context.Context, *GetAdminRequest) (*GetAdminResponse, error)
	DeleteAdmin(context.Context, *DeleteAdminRequest) (*DeleteAdminResponse, error)
	LoginAdmin(context.Context, *LoginAdminRequest) (*LoginAdminResponse, error)
	//
	//================================================================
	//SPONSOR RPC CALLS
	//================================================================
	CreateSponsor(context.Context, *CreateSponsorRequest) (*CreateSponsorResponse, error)
	CreateCompany(context.Context, *CreateCompanyRequest) (*CreateCompanyResponse, error)
}

func RegisterSponsorServiceServer(s *grpc.Server, srv SponsorServiceServer) {
	s.RegisterService(&_SponsorService_serviceDesc, srv)
}

func _SponsorService_CreateAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SponsorServiceServer).CreateAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SponsorService/CreateAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SponsorServiceServer).CreateAdmin(ctx, req.(*CreateAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SponsorService_GetAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SponsorServiceServer).GetAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SponsorService/GetAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SponsorServiceServer).GetAdmin(ctx, req.(*GetAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SponsorService_DeleteAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SponsorServiceServer).DeleteAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SponsorService/DeleteAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SponsorServiceServer).DeleteAdmin(ctx, req.(*DeleteAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SponsorService_LoginAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SponsorServiceServer).LoginAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SponsorService/LoginAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SponsorServiceServer).LoginAdmin(ctx, req.(*LoginAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SponsorService_CreateSponsor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSponsorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SponsorServiceServer).CreateSponsor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SponsorService/CreateSponsor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SponsorServiceServer).CreateSponsor(ctx, req.(*CreateSponsorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SponsorService_CreateCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SponsorServiceServer).CreateCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SponsorService/CreateCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SponsorServiceServer).CreateCompany(ctx, req.(*CreateCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SponsorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SponsorService",
	HandlerType: (*SponsorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAdmin",
			Handler:    _SponsorService_CreateAdmin_Handler,
		},
		{
			MethodName: "GetAdmin",
			Handler:    _SponsorService_GetAdmin_Handler,
		},
		{
			MethodName: "DeleteAdmin",
			Handler:    _SponsorService_DeleteAdmin_Handler,
		},
		{
			MethodName: "LoginAdmin",
			Handler:    _SponsorService_LoginAdmin_Handler,
		},
		{
			MethodName: "CreateSponsor",
			Handler:    _SponsorService_CreateSponsor_Handler,
		},
		{
			MethodName: "CreateCompany",
			Handler:    _SponsorService_CreateCompany_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sponsor.proto",
}
