// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sponsor.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginAdminRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAdminRequest) Reset()         { *m = LoginAdminRequest{} }
func (m *LoginAdminRequest) String() string { return proto.CompactTextString(m) }
func (*LoginAdminRequest) ProtoMessage()    {}
func (*LoginAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{0}
}

func (m *LoginAdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAdminRequest.Unmarshal(m, b)
}
func (m *LoginAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAdminRequest.Marshal(b, m, deterministic)
}
func (m *LoginAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAdminRequest.Merge(m, src)
}
func (m *LoginAdminRequest) XXX_Size() int {
	return xxx_messageInfo_LoginAdminRequest.Size(m)
}
func (m *LoginAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAdminRequest proto.InternalMessageInfo

func (m *LoginAdminRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginAdminRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginAdminResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAdminResponse) Reset()         { *m = LoginAdminResponse{} }
func (m *LoginAdminResponse) String() string { return proto.CompactTextString(m) }
func (*LoginAdminResponse) ProtoMessage()    {}
func (*LoginAdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{1}
}

func (m *LoginAdminResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAdminResponse.Unmarshal(m, b)
}
func (m *LoginAdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAdminResponse.Marshal(b, m, deterministic)
}
func (m *LoginAdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAdminResponse.Merge(m, src)
}
func (m *LoginAdminResponse) XXX_Size() int {
	return xxx_messageInfo_LoginAdminResponse.Size(m)
}
func (m *LoginAdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAdminResponse proto.InternalMessageInfo

func (m *LoginAdminResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DeleteAdminRequest struct {
	AdminID              string   `protobuf:"bytes,1,opt,name=adminID,proto3" json:"adminID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAdminRequest) Reset()         { *m = DeleteAdminRequest{} }
func (m *DeleteAdminRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAdminRequest) ProtoMessage()    {}
func (*DeleteAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{2}
}

func (m *DeleteAdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAdminRequest.Unmarshal(m, b)
}
func (m *DeleteAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAdminRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAdminRequest.Merge(m, src)
}
func (m *DeleteAdminRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAdminRequest.Size(m)
}
func (m *DeleteAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAdminRequest proto.InternalMessageInfo

func (m *DeleteAdminRequest) GetAdminID() string {
	if m != nil {
		return m.AdminID
	}
	return ""
}

type DeleteAdminResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAdminResponse) Reset()         { *m = DeleteAdminResponse{} }
func (m *DeleteAdminResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAdminResponse) ProtoMessage()    {}
func (*DeleteAdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{3}
}

func (m *DeleteAdminResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAdminResponse.Unmarshal(m, b)
}
func (m *DeleteAdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAdminResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAdminResponse.Merge(m, src)
}
func (m *DeleteAdminResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAdminResponse.Size(m)
}
func (m *DeleteAdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAdminResponse proto.InternalMessageInfo

func (m *DeleteAdminResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type CreateAdminRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PasswordPlainText    string   `protobuf:"bytes,3,opt,name=passwordPlainText,proto3" json:"passwordPlainText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAdminRequest) Reset()         { *m = CreateAdminRequest{} }
func (m *CreateAdminRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAdminRequest) ProtoMessage()    {}
func (*CreateAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{4}
}

func (m *CreateAdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAdminRequest.Unmarshal(m, b)
}
func (m *CreateAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAdminRequest.Marshal(b, m, deterministic)
}
func (m *CreateAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAdminRequest.Merge(m, src)
}
func (m *CreateAdminRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAdminRequest.Size(m)
}
func (m *CreateAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAdminRequest proto.InternalMessageInfo

func (m *CreateAdminRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateAdminRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateAdminRequest) GetPasswordPlainText() string {
	if m != nil {
		return m.PasswordPlainText
	}
	return ""
}

type CreateAdminResponse struct {
	Admin                *Admin   `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAdminResponse) Reset()         { *m = CreateAdminResponse{} }
func (m *CreateAdminResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAdminResponse) ProtoMessage()    {}
func (*CreateAdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{5}
}

func (m *CreateAdminResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAdminResponse.Unmarshal(m, b)
}
func (m *CreateAdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAdminResponse.Marshal(b, m, deterministic)
}
func (m *CreateAdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAdminResponse.Merge(m, src)
}
func (m *CreateAdminResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAdminResponse.Size(m)
}
func (m *CreateAdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAdminResponse proto.InternalMessageInfo

func (m *CreateAdminResponse) GetAdmin() *Admin {
	if m != nil {
		return m.Admin
	}
	return nil
}

type GetAdminRequest struct {
	AdminID              string   `protobuf:"bytes,1,opt,name=adminID,proto3" json:"adminID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAdminRequest) Reset()         { *m = GetAdminRequest{} }
func (m *GetAdminRequest) String() string { return proto.CompactTextString(m) }
func (*GetAdminRequest) ProtoMessage()    {}
func (*GetAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{6}
}

func (m *GetAdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAdminRequest.Unmarshal(m, b)
}
func (m *GetAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAdminRequest.Marshal(b, m, deterministic)
}
func (m *GetAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdminRequest.Merge(m, src)
}
func (m *GetAdminRequest) XXX_Size() int {
	return xxx_messageInfo_GetAdminRequest.Size(m)
}
func (m *GetAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdminRequest proto.InternalMessageInfo

func (m *GetAdminRequest) GetAdminID() string {
	if m != nil {
		return m.AdminID
	}
	return ""
}

type GetAdminResponse struct {
	Admin                *Admin   `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAdminResponse) Reset()         { *m = GetAdminResponse{} }
func (m *GetAdminResponse) String() string { return proto.CompactTextString(m) }
func (*GetAdminResponse) ProtoMessage()    {}
func (*GetAdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{7}
}

func (m *GetAdminResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAdminResponse.Unmarshal(m, b)
}
func (m *GetAdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAdminResponse.Marshal(b, m, deterministic)
}
func (m *GetAdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdminResponse.Merge(m, src)
}
func (m *GetAdminResponse) XXX_Size() int {
	return xxx_messageInfo_GetAdminResponse.Size(m)
}
func (m *GetAdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdminResponse proto.InternalMessageInfo

func (m *GetAdminResponse) GetAdmin() *Admin {
	if m != nil {
		return m.Admin
	}
	return nil
}

type Admin struct {
	AdminID              string   `protobuf:"bytes,1,opt,name=adminID,proto3" json:"adminID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	ACL                  []string `protobuf:"bytes,5,rep,name=ACL,proto3" json:"ACL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Admin) Reset()         { *m = Admin{} }
func (m *Admin) String() string { return proto.CompactTextString(m) }
func (*Admin) ProtoMessage()    {}
func (*Admin) Descriptor() ([]byte, []int) {
	return fileDescriptor_b93c2e50814def43, []int{8}
}

func (m *Admin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Admin.Unmarshal(m, b)
}
func (m *Admin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Admin.Marshal(b, m, deterministic)
}
func (m *Admin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Admin.Merge(m, src)
}
func (m *Admin) XXX_Size() int {
	return xxx_messageInfo_Admin.Size(m)
}
func (m *Admin) XXX_DiscardUnknown() {
	xxx_messageInfo_Admin.DiscardUnknown(m)
}

var xxx_messageInfo_Admin proto.InternalMessageInfo

func (m *Admin) GetAdminID() string {
	if m != nil {
		return m.AdminID
	}
	return ""
}

func (m *Admin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Admin) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Admin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Admin) GetACL() []string {
	if m != nil {
		return m.ACL
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginAdminRequest)(nil), "proto.LoginAdminRequest")
	proto.RegisterType((*LoginAdminResponse)(nil), "proto.LoginAdminResponse")
	proto.RegisterType((*DeleteAdminRequest)(nil), "proto.DeleteAdminRequest")
	proto.RegisterType((*DeleteAdminResponse)(nil), "proto.DeleteAdminResponse")
	proto.RegisterType((*CreateAdminRequest)(nil), "proto.CreateAdminRequest")
	proto.RegisterType((*CreateAdminResponse)(nil), "proto.CreateAdminResponse")
	proto.RegisterType((*GetAdminRequest)(nil), "proto.GetAdminRequest")
	proto.RegisterType((*GetAdminResponse)(nil), "proto.GetAdminResponse")
	proto.RegisterType((*Admin)(nil), "proto.Admin")
}

func init() { proto.RegisterFile("sponsor.proto", fileDescriptor_b93c2e50814def43) }

var fileDescriptor_b93c2e50814def43 = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xd1, 0x6a, 0xd4, 0x40,
	0x14, 0x65, 0x93, 0x46, 0xb7, 0x77, 0xb5, 0x76, 0x6f, 0xa5, 0x4d, 0xe3, 0x0a, 0x65, 0x44, 0x28,
	0xab, 0x6c, 0xb0, 0x82, 0x60, 0xdf, 0x4a, 0x0b, 0x22, 0xf6, 0x41, 0x52, 0x3f, 0xc0, 0xa9, 0xbd,
	0x2c, 0xc3, 0x66, 0x67, 0x62, 0x32, 0xad, 0x8a, 0xf8, 0xe2, 0x2f, 0xf8, 0x13, 0xfe, 0x8f, 0xbf,
	0xe0, 0x87, 0x48, 0x66, 0x26, 0x69, 0xb2, 0x89, 0x62, 0x9f, 0x76, 0xee, 0xde, 0x93, 0x73, 0xee,
	0x39, 0x73, 0x07, 0xee, 0x16, 0x99, 0x92, 0x85, 0xca, 0x67, 0x59, 0xae, 0xb4, 0xc2, 0xc0, 0xfc,
	0x44, 0x93, 0xb9, 0x52, 0xf3, 0x94, 0x62, 0x9e, 0x89, 0x98, 0x4b, 0xa9, 0x34, 0xd7, 0x42, 0xc9,
	0xc2, 0x82, 0xd8, 0x1b, 0x18, 0x9f, 0xaa, 0xb9, 0x90, 0x47, 0x17, 0x4b, 0x21, 0x13, 0xfa, 0x78,
	0x49, 0x85, 0xc6, 0x08, 0x86, 0x97, 0x05, 0xe5, 0x92, 0x2f, 0x29, 0x1c, 0xec, 0x0d, 0xf6, 0xd7,
	0x93, 0xba, 0x2e, 0x7b, 0x19, 0x2f, 0x8a, 0x4f, 0x2a, 0xbf, 0x08, 0x3d, 0xdb, 0xab, 0x6a, 0x36,
	0x05, 0x6c, 0x92, 0x99, 0x71, 0x08, 0xef, 0x43, 0xa0, 0xd5, 0x82, 0xa4, 0xa3, 0xb2, 0x05, 0x9b,
	0x01, 0x9e, 0x50, 0x4a, 0x9a, 0x5a, 0xca, 0x21, 0xdc, 0xe6, 0x65, 0xfd, 0xfa, 0xc4, 0xa1, 0xab,
	0x92, 0x3d, 0x86, 0xad, 0x16, 0xde, 0x91, 0x6f, 0x80, 0xa7, 0x16, 0x06, 0x3b, 0x4c, 0x3c, 0xb5,
	0x60, 0x29, 0xe0, 0x71, 0x4e, 0x7c, 0x85, 0x16, 0x61, 0xad, 0x61, 0xc6, 0x9c, 0xcb, 0xb1, 0x68,
	0xc9, 0x45, 0xea, 0x5c, 0xd8, 0x02, 0x9f, 0xc2, 0xb8, 0xb2, 0xf3, 0x36, 0xe5, 0x42, 0xbe, 0xa3,
	0xcf, 0x3a, 0xf4, 0x0d, 0xa2, 0xdb, 0x60, 0x2f, 0x61, 0xab, 0xa5, 0xe6, 0x86, 0x62, 0x10, 0x98,
	0xb1, 0x8d, 0xde, 0xe8, 0xe0, 0x8e, 0xcd, 0x7a, 0x66, 0x41, 0xb6, 0xc5, 0x9e, 0xc0, 0xbd, 0x57,
	0xa4, 0xff, 0xd3, 0xfc, 0x0b, 0xd8, 0xbc, 0x06, 0xdf, 0x40, 0xe4, 0x0b, 0x04, 0xa6, 0xfe, 0x3b,
	0x75, 0x1d, 0x8d, 0xd7, 0x17, 0x8d, 0xdf, 0x8c, 0xa6, 0x79, 0xf3, 0x6b, 0xed, 0x9b, 0xc7, 0x4d,
	0xf0, 0x8f, 0x8e, 0x4f, 0xc3, 0x60, 0xcf, 0xdf, 0x5f, 0x4f, 0xca, 0xe3, 0xc1, 0x4f, 0x1f, 0x36,
	0xce, 0xec, 0x3e, 0x9e, 0x51, 0x7e, 0x25, 0x3e, 0x10, 0x9e, 0xc3, 0xa8, 0x91, 0x16, 0xee, 0xba,
	0x89, 0xbb, 0xf7, 0x15, 0x45, 0x7d, 0x2d, 0xeb, 0x9b, 0x4d, 0xbe, 0xff, 0xfa, 0xfd, 0xc3, 0xdb,
	0x66, 0xe3, 0xf8, 0xea, 0x59, 0xec, 0x36, 0x3e, 0x36, 0x6e, 0x0e, 0x07, 0x53, 0x7c, 0x0f, 0xc3,
	0x2a, 0x29, 0xdc, 0x76, 0x2c, 0x2b, 0x39, 0x47, 0x3b, 0x9d, 0xff, 0x1d, 0xf5, 0x23, 0x43, 0xfd,
	0x10, 0x1f, 0x74, 0xa8, 0xe3, 0xaf, 0x2e, 0xaf, 0x6f, 0x28, 0x60, 0xd4, 0x58, 0xc4, 0xda, 0x45,
	0x77, 0x99, 0x6b, 0x17, 0x3d, 0x7b, 0x5b, 0x49, 0x4d, 0xff, 0x29, 0x45, 0x00, 0xd7, 0xef, 0x09,
	0x43, 0x47, 0xd7, 0x79, 0xaf, 0xd1, 0x6e, 0x4f, 0xc7, 0xe9, 0x30, 0xa3, 0x33, 0x61, 0x3b, 0x5d,
	0x9d, 0xb4, 0x44, 0x1f, 0x0e, 0xa6, 0xe7, 0xb7, 0xcc, 0xd7, 0xcf, 0xff, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x71, 0xe1, 0x00, 0x82, 0x40, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SponsorServiceClient is the client API for SponsorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SponsorServiceClient interface {
	CreateAdmin(ctx context.Context, in *CreateAdminRequest, opts ...grpc.CallOption) (*CreateAdminResponse, error)
	GetAdmin(ctx context.Context, in *GetAdminRequest, opts ...grpc.CallOption) (*GetAdminResponse, error)
	DeleteAdmin(ctx context.Context, in *DeleteAdminRequest, opts ...grpc.CallOption) (*DeleteAdminResponse, error)
	LoginAdmin(ctx context.Context, in *LoginAdminRequest, opts ...grpc.CallOption) (*LoginAdminResponse, error)
}

type sponsorServiceClient struct {
	cc *grpc.ClientConn
}

func NewSponsorServiceClient(cc *grpc.ClientConn) SponsorServiceClient {
	return &sponsorServiceClient{cc}
}

func (c *sponsorServiceClient) CreateAdmin(ctx context.Context, in *CreateAdminRequest, opts ...grpc.CallOption) (*CreateAdminResponse, error) {
	out := new(CreateAdminResponse)
	err := c.cc.Invoke(ctx, "/proto.SponsorService/CreateAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sponsorServiceClient) GetAdmin(ctx context.Context, in *GetAdminRequest, opts ...grpc.CallOption) (*GetAdminResponse, error) {
	out := new(GetAdminResponse)
	err := c.cc.Invoke(ctx, "/proto.SponsorService/GetAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sponsorServiceClient) DeleteAdmin(ctx context.Context, in *DeleteAdminRequest, opts ...grpc.CallOption) (*DeleteAdminResponse, error) {
	out := new(DeleteAdminResponse)
	err := c.cc.Invoke(ctx, "/proto.SponsorService/DeleteAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sponsorServiceClient) LoginAdmin(ctx context.Context, in *LoginAdminRequest, opts ...grpc.CallOption) (*LoginAdminResponse, error) {
	out := new(LoginAdminResponse)
	err := c.cc.Invoke(ctx, "/proto.SponsorService/LoginAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SponsorServiceServer is the server API for SponsorService service.
type SponsorServiceServer interface {
	CreateAdmin(context.Context, *CreateAdminRequest) (*CreateAdminResponse, error)
	GetAdmin(context.Context, *GetAdminRequest) (*GetAdminResponse, error)
	DeleteAdmin(context.Context, *DeleteAdminRequest) (*DeleteAdminResponse, error)
	LoginAdmin(context.Context, *LoginAdminRequest) (*LoginAdminResponse, error)
}

func RegisterSponsorServiceServer(s *grpc.Server, srv SponsorServiceServer) {
	s.RegisterService(&_SponsorService_serviceDesc, srv)
}

func _SponsorService_CreateAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SponsorServiceServer).CreateAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SponsorService/CreateAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SponsorServiceServer).CreateAdmin(ctx, req.(*CreateAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SponsorService_GetAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SponsorServiceServer).GetAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SponsorService/GetAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SponsorServiceServer).GetAdmin(ctx, req.(*GetAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SponsorService_DeleteAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SponsorServiceServer).DeleteAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SponsorService/DeleteAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SponsorServiceServer).DeleteAdmin(ctx, req.(*DeleteAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SponsorService_LoginAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SponsorServiceServer).LoginAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SponsorService/LoginAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SponsorServiceServer).LoginAdmin(ctx, req.(*LoginAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SponsorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SponsorService",
	HandlerType: (*SponsorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAdmin",
			Handler:    _SponsorService_CreateAdmin_Handler,
		},
		{
			MethodName: "GetAdmin",
			Handler:    _SponsorService_GetAdmin_Handler,
		},
		{
			MethodName: "DeleteAdmin",
			Handler:    _SponsorService_DeleteAdmin_Handler,
		},
		{
			MethodName: "LoginAdmin",
			Handler:    _SponsorService_LoginAdmin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sponsor.proto",
}
